name: Build CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Back-End
      run: mvn -B package --file pom.xml
       
    - name: Setup NPM
      uses: actions/setup-node@v3
      with:
        node-version: 14
    
    - name: Build Front-End
      working-directory: ./src/main/webapp
      run: npm run build
      
